// Generated by wrangler types — run `pnpm gen` to regenerate
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
